apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harsha190202/Istio.git
    targetRevision: main
    path: app-charts/products
  destination:
    server: "https://kubernetes.default.svc"
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
