apiVersion: v1
kind: Namespace
metadata:
  name: applications

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
